required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen"
]

[[constraint]]
  name = "github.com/go-openapi/spec"
  revision = "6aced65f8501fe1217321abf0749d354824ba2ff"

[[constraint]]
  name = "github.com/golang/glog"
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  revision = "e7e903064f5e9eb5da98208bae10b475d4db0f8c"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "v1.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.9.2"

[[constraint]]
  branch = "release-6.0"
  name = "k8s.io/client-go"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.9.2"

# [[override]]
#   name = "k8s.io/gengo"
#   revision = "8394c995ab8fbe52216f38d0e1a37de36d820528"

[[constraint]]
  name = "k8s.io/kube-openapi"
  revision = "50ae88d24ede7b8bad68e23c805b5d3da5c8abaf"

[[override]]
  name = "cloud.google.com/go"
  version = "0.18.0"

[[constraint]]
  name = "github.com/gophercloud/gophercloud"
  revision = "fe85f9519740a5b5c09ecb0909609b58e59e5dec"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false

[[constraint]]
  name = "github.com/aliyun/alibaba-cloud-sdk-go"
  version = "1.9.1"
