# Sample Azure machine class

apiVersion: machine.sapcloud.io/v1alpha1
kind: AzureMachineClass
metadata:
  name: test-azure # Name of Azure machine class goes here
  namespace: default # Namespace in which the machine class is to be deployed
spec:
  location: "sample-location" # Azure location in which machine is to be deployed (Eg- NorthAmerica)
  resourceGroup: "sample-resource-group" # Name of the resource group to which the node should be bound
  subnetInfo:
    vnetName: "sample-vnet" # The V-Net to which the node should belong
    subnetName: "sample-subnet-in-given-vnet" # The subnet to which the node should belong
  secretRef: # Kubernetes secret containing values for provider secrets and user-data
    name: "test-secret" # Name of the secret
    namespace: "default" # Namespace of secret
  tags:
    kubernetes.io-cluster-YOUR_CLUSTER_NAME: "1" # This is mandatory as the safety controller uses this tag to identify VMs created by this controller.
    kubernetes.io-role-YOUR_ROLE_NAME: "1" # This is mandatory as the safety controller uses this tag to identify VMs created by this controller.
    tag1: "key1" # A set of additional tags attached to a machine (optional)
    tag2: "key2" # A set of additional tags attached to a machine (optional)
  properties:
    hardwareProfile:
      vmSize: "sample-azure-vm-size" # VMsize based on azure machine kinds (Eg- Standard_DS1_V2)
    storageProfile:
      imageReference:
        urn: "image-reference-urn" # Image reference urn, it has the format 'publisher:offer:sku:version' (Eg- "CoreOS:CoreOS:Beta:1000.0.0")
      osDisk:
        caching: "None" # Caching Strategy (None/ReadOnly/ReadWrite)
        diskSizeGB: 50 # Size of disk to be created in GB
        createOption: "FromImage" # Create option for disk (Empty/Attach/FromImage)
    osProfile:
      adminUsername: "admin-name" # Admin user name
      linuxConfiguration:
        disablePasswordAuthentication: true # Disable password authentication
        ssh:
          publicKeys:
            path: "/path/to/public-key/in/machine" # Path to public key
            keyData: "public-key-data" # Public key data
    identityID: "/subscriptions/subscription-id/resourceGroups/resource-group-name/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name" # ID of an user assigned managed identity to attach the machine to
    zone: 1 # Zone which the node will be deployed into. Either a zone or an AvailabilitySet can be specified.
    availabilitySet: # AvailabilitySet which the node will be assigned to. Either a zone or an AvailabilitySet can be specified.
      id: "/subscriptions/subscription-id/resourceGroups/resource-group-name/providers/Microsoft.Compute/availabilitySets/availablity-set-name" # ID of availability set to attach the machine to
