# Sample OpenStack machine class

apiVersion: machine.sapcloud.io/v1alpha1
kind: OpenStackMachineClass
metadata:
  name: test-openstack # Name of OpenStack machine class goes here
  namespace: default # Namespace in which the machine class is to be deployed
spec:
  flavorName: <flavor_name> # Name of the machine flavor
  keyName: <keypair_name> # Name of the ssh key pair
  imageName: <image_name> # Machine image name
  imageID: <image_name> # Machine image id (either name or id needs to be present)
  networkID: <network_id> # Network ID where the machine should be placed
  securityGroups:
  - <security_group_name> # List of security groups which should be used for this machine
  region: <region> # Region where to place the machine
  availabilityZone: <availability_zone> # Availability zone where to place the machine
  podNetworkCidr: <pod_network_cidr> # CIDR of the overlay Calico IP pool
  # rootDiskSize: 100 # in GB (optional) overrides the flavor provider root disk size and use a Cinder backed block device instead
  # OpenStack machine metadata block
  # Be aware, that metadata keys (tags) in OpenStack can not contain special characters likes "/"
  tags:
    kubernetes.io-cluster-YOUR_CLUSTER_NAME: "1" # This is mandatory as the safety controller uses this tag to identify VMs created by this controller.
    kubernetes.io-role-YOUR_ROLE_NAME: "1" # This is mandatory as the safety controller uses this tag to identify VMs created by this controller.
    tag1: tag1-value # A set of additional tags attached to a machine (optional)
    tag2: tag2-value # A set of additional tags attached to a machine (optional)
  secretRef: # Secret pointing to a secret which contains the provider secret and cloudconfig
    namespace: default  # Namespace
    name: test-secret # Name of the secret
