# Sample secret

apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  userData: "encoded-cloud-config" # AWS cloud config file (base64 encoded)
  azureClientId: "azure-client-id" # Azure client id (base64 encoded)
  azureClientSecret: "azure-client-secret" # Azure client secret (base64 encoded)
  azureSubscriptionId: "azure-subscription-id" # Azure subscription id (base64 encoded)
  azureTenantId: "azure-tenant-id" # Azure tenant id (base64 encoded)
### Alternative data keys are:
# clientID: "azure-client-id" # Azure client id (base64 encoded)
# clientSecret: "azure-client-secret" # Azure client secret (base64 encoded)
# subscriptionID: "azure-subscription-id" # Azure subscription id (base64 encoded)
# tenantID: "azure-tenant-id" # Azure tenant id (base64 encoded)
type: Opaque
