# Sample secret for GCP

apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  userData: "encoded-cloud-config" # GCP cloud config file (base64 encoded)
  serviceAccountJSON: "{...}" # GCP service account json object (base64 encoded)
### Alternative data keys are:
# serviceaccount.json: "{...}" # GCP service account json object (base64 encoded)
type: Opaque
