# Sample secret for GCP

apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  userData: "encoded-cloud-config" # packet cloud config file (base64 encoded)
  apiToken: "{...}" # packet API key (base64 encoded)
type: Opaque
