# Sample machine-deploy object

apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineDeployment
metadata:
  name: test-machine-deployment # Name of the machine deploy
  namespace: default
spec:
  #paused: true [uncommment this when you want to pause]
  #rollbackTo:
    #revision: 0 [uncommment this when you want to rollback to previous version]
  replicas: 3 # Number of healthy replicas that should always be healthy
  minReadySeconds: 500 # Minimum time to wait for machine to be ready
  strategy:
    type: RollingUpdate # Strategy for update RollingUpdate/Recreate
    rollingUpdate:
      maxSurge: 1 # Maximum addition machines that spawned over the desired replicas during update
      maxUnavailable: 1 # Maximum unavailable machines that the cluster can tolerate
  selector:
    matchLabels:
      test-label: test-label # Label to match the template (XXXXX)
  template:
    metadata:
      labels:
        test-label: test-label # Label to match with selector (XXXXX)
    spec:
      class:
        kind: AWSMachineClass # Machine class template used to create machine, could be AWS/GCP/Azure/Other-cloud-providers
        name: test-aws # Name of the machine class
    # drainTimeout: 5m
    # healthTimeout: 5m
    # creationTimeout: 5m
    # maxEvictRetries: 25
    # nodeConditions: "ReadonlyFilesystem,KernelDeadlock,DiskPressure"