# The set of CRDs used by machine-controller-manager

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machineclasses.machine.sapcloud.io
spec:
  group: machine.sapcloud.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: MachineClass
    plural: machineclasses
    singular: machineclass
    shortNames:
    - machcls

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machines.machine.sapcloud.io
spec:
  group: machine.sapcloud.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Machine
    plural: machines
    singular: machine
    shortNames:
    - mach

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machinesets.machine.sapcloud.io
spec:
  group: machine.sapcloud.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: MachineSet
    plural: machinesets
    singular: machineset
    shortNames:
    - machset

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machinedeployments.machine.sapcloud.io
spec:
  group: machine.sapcloud.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: MachineDeployment
    plural: machinedeployments
    singular: machinedeployment
    shortNames:
    - machdeploy
